# Generated by Django 5.2 on 2025-05-22 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empleado', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empleados',
            new_name='Empleado',
        ),
    ]
