# Generated by Django 5.2 on 2025-05-22 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Casa', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empleado',
            new_name='Casa',
        ),
    ]
