# Generated by Django 5.2 on 2025-05-22 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Casa', '0002_rename_empleado_casa'),
        ('Empleado', '0002_rename_empleados_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstalacionCaptacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Casa.casa')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empleado.empleado')),
            ],
        ),
    ]
